// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfu7NJryVewKXtI-C2o6Wp_Gs7vvvJ30',
    appId: '1:302569543037:web:b44a2d7d02e263792e6814',
    messagingSenderId: '302569543037',
    projectId: 'flutter-pwd-container',
    authDomain: 'flutter-pwd-container.firebaseapp.com',
    storageBucket: 'flutter-pwd-container.firebasestorage.app',
    measurementId: 'G-7Q2MEHDCWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHK84URQzDlb7jgTnDCwqwblLYHG5aiN8',
    appId: '1:302569543037:android:a1dee80b16f2c7bc2e6814',
    messagingSenderId: '302569543037',
    projectId: 'flutter-pwd-container',
    storageBucket: 'flutter-pwd-container.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB27ZMg6K1J7xOoaFKVpqu-eFHstTJUbw',
    appId: '1:302569543037:ios:f1893744c031be662e6814',
    messagingSenderId: '302569543037',
    projectId: 'flutter-pwd-container',
    storageBucket: 'flutter-pwd-container.firebasestorage.app',
    iosClientId: '302569543037-p4elpogg1660g0ismrfam57km7r173bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPwdContainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB27ZMg6K1J7xOoaFKVpqu-eFHstTJUbw',
    appId: '1:302569543037:ios:f1893744c031be662e6814',
    messagingSenderId: '302569543037',
    projectId: 'flutter-pwd-container',
    storageBucket: 'flutter-pwd-container.firebasestorage.app',
    iosClientId: '302569543037-p4elpogg1660g0ismrfam57km7r173bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPwdContainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfu7NJryVewKXtI-C2o6Wp_Gs7vvvJ30',
    appId: '1:302569543037:web:7411ef02a1bb1cf02e6814',
    messagingSenderId: '302569543037',
    projectId: 'flutter-pwd-container',
    authDomain: 'flutter-pwd-container.firebaseapp.com',
    storageBucket: 'flutter-pwd-container.firebasestorage.app',
    measurementId: 'G-8GLMKJQKS1',
  );
}
